name: Develop Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: [self-hosted, deploy-develop]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Build
        run: docker build . --file Dockerfile --tag xivrepo/apiserver-develop:${{ github.sha }}

      -
        name: Deploy
        run: |
          pushd /compose/develop-api-server
          TAG=${{ github.sha }} docker-compose up -d
          popd
